import React, { Component } from 'react';
import fetch from 'isomorphic-unfetch';
import axios from 'axios';
import Router from 'next/router';
import Header from '../components/Header';
import Menu from '../components/Menu';
import Footer from '../components/Footer';
import JScookie from 'js-cookie';
import $ from  '../node_modules/jquery/dist/jquery.min.js';

// Live
var baseURL = process.env.BASEURL;

export default class extends Component {
	
	constructor(props, context) {
		super(props, context);
    }
	
  render() {
	return (
		<div>
			<Header title="Terms & Conditions - Get my formula" />
			<div className="science-page terms-page">
				<section>
					<div className="product-header-bg">
						<div className="container container-header">
							<div className="row">
								<div className="col-lg-12">
									<Menu />
								</div>
							</div>
						</div>
					</div>
				</section>
                 <section>
                    <div className="container">
                        <div className="row">
                            <div className="col-lg-12 col-md-12 col-sm-12">
                                <div className="main-medical-heading text-center">
                                    <h1>Terms and Conditions</h1>
                                    <h3>CAREFULLY READ THESE TERMS & CONDITIONS BEFORE ORDERING</h3>
                                </div>
                                <div className="disclaimer-heading">
                                    <h2>INTRODUCTION</h2>
        
                                    <p>These Terms and Conditions (“Agreement” or “Terms”) constitute a binding written agreement between OUTLIERS INC., and its affiliated entities (collectively “Company,” “we,” “us,” or “our”) and you (“you” or “Customer”). To make these Terms easier to read, the services offered by the Website are collectively called “Services.”</p>
      
                                    <p>This Website is operated by the Company. PLEASE READ THIS AGREEMENT CAREFULLY BEFORE USING THIS WEBSITE. THESE TERMS OF USE DESCRIBE YOUR LEGAL RIGHTS AND RESPONSIBILITIES, AND BY ACCESSING OR USING THE WEBSITE OR SERVICE, YOU ACCEPT AND AGREE TO BE BOUND AND ABIDE BY THIS AGREEMENT. THESE TERMS FORM A LEGAL AGREEMENT BETWEEN YOU AND US REGARDING YOUR USE OF THE SITE ALONG WITH THE RELATED SERVICES, FEATURES, CONTENT, AND OFFERS PROVIDED ON THE WEBSITE. THESE TERMS ALSO INCLUDE A MANDATORY ARBITRATION CLAUSE. IF YOU ARE NOT WILLING TO BE BOUND BY THESE TERMS, INCLUDING THE DISCLAIMERS, YOU MAY NOT ACCESS OR USE THIS WEBSITE. IF YOU DO NOT UNDERSTAND AND AGREE TO ALL OF THESE TERMS, OR ARE UNDER EIGHTEEN (18) YEARS OF AGE, YOU SHOULD CEASE ALL USE OF OUR SITES AND LOGOFF IMMEDIATELY. Your use of this Website, purchase or use of any of our products constitutes your agreement to these Terms and Conditions.</p>
      
                                    <h3>ACCEPTANCE OF TERMS AND CONDITIONS</h3>
                                        
                                    <p>By making any use of our Websites (“Website” or “sites”), Services, and any purchase from us, you expressly agree to the terms contained herein.</p>
                                    <p>You consent and agree that your use of a keypad, mouse or other device to select an item, button, icon, checkbox, to enter text, or to perform a similar act/action, while using our sites, for the purpose of accessing or making any transactions regarding any agreement, acknowledgment, consent, terms, disclosures or conditions, constitutes your signature, including without limitation of the United States Electronic Signatures in Global and National Commerce Act, P.L. 106-229 (the “E-Sign Act”) acceptance and agreement as if actually signed by you in writing. Be advised that all activity and IP address information may be monitored. The right to use any product or service you purchase from us is personal to you and is not transferable to any other person or entity.</p>
                                    <h3>CHANGES TO TERMS OR SERVICES</h3>
                                  <p>The Company reserves the right to make changes to the sites, policies, and to this Agreement at any time and without notice. YOU SHOULD PRINT A COPY OF THIS AGREEMENT AND CHECK BACK FREQUENTLY FOR UPDATES. Your continued use of our sites or of any purchased product or service following any future amendment constitutes your acceptance of any modified terms. If you have any questions regarding these terms, please contact customer care at daniel@getmyformula.com.</p>
                                  <h3>SITE CONTENT AND CONTENT RIGHTS</h3>
                                  <p>For purposes of these Terms: (i) “Content” means text, graphics, images, music, software, audio, video, works of authorship of any kind, and information or other materials that are posted, generated, provided or otherwise made available through the Services or sites; and (ii) “User Content” means any Content that Account holders (including you) provide to be made available through the Services or sites. Content includes without limitation User Content. Any information submitted on the site is subject to the terms of which are incorporated herein.</p>
                                <p>The Company neither endorses nor is responsible for the accuracy or reliability of any opinion or statement on the sites, nor for any offensive, defamatory or obscene posting made by any user. Under no circumstances will Company be liable for any loss or damage caused by your reliance on information obtained through the content on the sites. It is your responsibility to evaluate the accuracy, completeness and usefulness of any information, opinion or other content available through the sites. Please seek the advice of professionals, as appropriate, regarding the evaluation of any specific information, opinion or other content, including but not limited to financial, health, or lifestyle information, opinion or other content.</p>
                              <h3>REVIEWS, COMMENTS, E-MAILS, AND OTHER CONTENT; OWNERSHIP AND REMOVAL</h3>
                              <p>Visitors and users may post reviews, comments, and other content, and submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of “spam.” You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. Company reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content. If you do post content or submit material, and unless we indicate otherwise, you grant Company and its associates a nonexclusive, royalty-free, perpetual, irrevocable, and fully sub licensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant Company and its associates and sublicensees the right to use the name that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the Content that you post; that the Content is accurate; that use of the Content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify Company or its associates for all claims resulting from Content you supply. Company has the right but not the obligation to monitor and edit or remove any activity or content. Company takes no responsibility and assumes no liability for any Content posted by you or any third party.</p>
                             <p>You can remove your User Content by deleting it. However, in certain instances some of your User Content (such as posts or comments you make) may not be completely removed and copies of your User Content may continue to exist on the sites. Company and its associates are not responsible or liable for the removal or deletion of (or the failure to remove or delete) any of your User Content.</p>
                          <h3>LIMITED RIGHT TO USE</h3>
                          <p>The viewing, printing or downloading of any Content, graphic, form, or document from the site grants you only a limited, non-exclusive license for use solely by you for your own personal, non-commercial use. You may not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or offer for sale any information contained on, or obtained from, the site. Illegal and/or unauthorized uses of the site, including collecting usernames and/or email addresses of members by electronic or other means for the purpose of sending unsolicited commercial email; using any information retrieval system, whether electronic or through other means, to reproduce any of the Content of the site other than for your personal use; and unauthorized framing or linking to the site will be investigated and appropriate legal action will be taken, including civil, criminal, and injunctive redress.</p>
                          <h3>DISCLAIMER OF WARRANTY</h3>
                          <p>The materials contained on the site are provided “as is” and without warranties of any kind either express or implied. To the fullest extent permissible pursuant to applicable law, we disclaim all warranties, express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, or other violations of rights. We assume no liability or responsibility for any errors or omissions in the content of the Services or site, that defects will be corrected, or that any Company site or the servers that make such materials available are free of viruses or other harmful components; any failures, delays, malfunctions, or interruptions in the delivery of any Content contained on the site; any losses or damages arising from the use of the content provided on the sites; or any conduct by users of the site, either online or offline. We do not warrant or make any representations regarding the use or the results of the use of the materials on any Services or sites in terms of their correctness, accuracy, reliability, or otherwise. You assume the entire cost of all necessary servicing, repair, or correction.</p>
                          <h3>LIMITATION OF LIABILITY</h3>
                          <p>Under no circumstances, including, but not limited to, negligence, shall Company, its officers, directors, employees, or agents be liable (jointly or severally) for any direct, indirect, special, incidental or consequential damages of any kind, including, but not limited to, loss of use, data, or profit, on any theory of liability, arising out of or in connection with the use or the inability to use the materials on the site, even if Company or any Company representative has been advised of the possibility of such damages. Some states do not allow the exclusion or limitation of incidental or consequential damages so the above limitation or exclusion may not apply to you. If any applicable authority holds any portion of this section to be unenforceable, then liability will be limited to the fullest extent permitted by applicable law.</p>
                        <h3>LINKS</h3>
                          <p>The site may provide links to other World Wide Web sites or resources not directly affiliated with Company. We have not reviewed these sites and is not responsible for the accuracy, content, privacy policies or availability of information found on sites that link to or from any Company site. We cannot ensure that you will be satisfied with any products or services that you purchase from a third-party site that links to or from any Company sites or third-party content on our sites. We do not endorse any of the merchandise, nor have we taken any steps to confirm the accuracy or reliability of any of the information contained in such third-party sites or content. We do not make any representations or warranties as to the security of any information (including, without limitation, credit card and other personal information) you might be requested to give any third party, and you hereby irrevocably waive any claim against Company with respect to such sites and third-party content. We strongly encourage you to make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. Neither Company nor its affiliates, employees, directors, officers, or agents shall be liable for any damages, including but not limited to direct, indirect, incidental, consequential, or punitive damages arising out of your use of third-party material or third-party sites that are linked to this site. No link to the site may be framed to the extent that such frame contains any sponsorship, advertising, or other commercial text or graphics. Deep linking to internal pages of this Website is expressly prohibited without prior written consent from Company.</p>
                          <h3>YOUR MEMBERSHIP ACCOUNT</h3>
                        <p>If you use this site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. If you are under eighteen (18) years of age, you may use our website only with involvement of a parent or guardian. Company and its associates reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders in their sole discretion.</p>
                          <h3>PRODUCT DESCRIPTIONS</h3>
                          <p>Company and its associates attempt to be as accurate as possible. However, Company does not warrant that product descriptions or other content of this site is accurate, complete, reliable, current, or error-free. If a product offered by Company itself is not as described, your sole remedy is to return it in unused condition.</p>
                          <h3>INDEMNITY</h3>
                          <p>You agree to defend, indemnify, and hold harmless Company, its officers, directors, employees, and agents, from and (i) against any claims, actions, or demands, including, but not limited to, reasonable legal and accounting fees, alleging or resulting from your use of the site or (ii) your breach of these Terms or (iii) your infringement of any intellectual property or privacy right of any person. Company shall provide notice to you promptly of any such claim, suit, or proceeding and shall assist you, at your expense, in defending any such claim, suit, or proceeding.</p>
                          <h3>DISPUTE RESOLUTION AND CHOICE OF LAW</h3>
                          <p>Any controversy or claim arising out of or relating to this contract, or the breach thereof, shall be settled by binding arbitration administered by the American Arbitration Association in accordance with its Commercial Arbitration Rules. The arbitration hearing shall take place in the Southern District of New York, before a single arbitrator. Judgment on the award rendered by the arbitrator may be entered in any court having jurisdiction thereof.</p>
                          <p>Further, you agree that any issue or dispute arising out of or in connection with your use of our site, intellectual property, the Terms, or any matter concerning Company shall be governed by the laws of the United States and the State of New York with venue in the Southern District of New York. If any provision of the Terms is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of the Terms, which shall remain in full force and effect.</p>
                          <p>By using the site, you agree to comply with all applicable laws and regulations of the United States. The material provided on the site is protected by law including, but not limited to, United States copyright and trademark law and international treaties. Company makes no representation that materials contained in the site are appropriate or available for use in other locations and access to them from territories where their contents are illegal is prohibited. Those who choose to access the Services or site from other locations outside the United States do so at their own initiative and are responsible for compliance with applicable local laws.</p>
                          <h3>TRADEMARKS</h3>
                          <p>This website and all of its contents including, but not limited to, articles, other text, photographs, illustrations, graphics, product names, designs, logos, and the collection, arrangement, and assembly of all content (collectively, “the Intellectual Property”) are protected by copyright, trademark, and other laws of the United States, as well as international conventions and the laws of other countries. The Intellectual Property is the exclusive property of Company. You specifically acknowledge that this Agreement does not confer upon you any interest in or right to use any trademark or service mark of Company or its Affiliates, unless you first receive the prior written consent of Company, which Company may grant or withhold in its sole discretion.</p>
                          <h3>COPYRIGHTS</h3>
                          <p>The copyright in all materials provided on the site is owned by Company or its affiliate(s).</p>
                          <p>Subject to the following exception, none of the material contained in the site may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means including, but not limited to, electronic, mechanical, photocopying, recording or otherwise, without the prior written consent of Company. Site visitors may only view, copy, print and download the materials on the site for personal, non-commercial use only, provided such materials are used for informational purposes only, and all copies, or portions thereof, include this copyright notice. We may revoke any of the foregoing rights at any time. Upon termination of any rights granted hereunder, you must immediately destroy any downloaded and printed materials. Any unauthorized use of any material contained on the site may violate copyright laws, trademark laws, the laws of privacy and publicity, and communications regulations and statutes.</p>
                          <h3>TERMINATION</h3>
                          <p>Company reserves the right to terminate your access to the site or any of its services if it determines that you do not comply with these Terms; provide false, inaccurate, or incomplete information during our registration process; engage in any conduct that would otherwise harm any of Company’s rights or interests in its site, services, or other property; or for any or no reason whatsoever without prior notice to you. Upon termination, you must cease use of the Services and site and destroy all materials obtained from such site and all copies thereof, whether made under these Terms or otherwise.</p>
                          <h3>LEGAL DISCLAIMER</h3>
                          <p>The information contained on this website is for informational use only and should not be construed as medical advice. Read the entire label before using any Company product, and follow all directions.</p>
                          <p>Statements made by Company have not been evaluated by the food and drug administration. The FDA does not evaluate or test herbs. These products are not intended to diagnose, treat, cure or prevent any illness or disease. Consult with your physician for diagnosis or treatment. Use products as per instructions and always watch for any allergic reactions.</p>
                          <p>The information presented on this site is not presented with the intention of diagnosing any disease or condition or prescribing any treatment.</p>
                          <p>In the event that any individual should use the information presented on this site without a licensed psychologist, medical doctor, psychiatrist or other appropriate professional healthcare provider’s approval, that individual will be diagnosing for him or herself.</p>
                          <p>No responsibility is assumed by the author, publisher or distributors of this information should the information be used in place of a licensed psychologist, medical doctor, psychiatrist or other appropriate professional health care provider’s services. No guarantees of any kind are made for the performance or effectiveness of the preparations mentioned on this website.</p>
                          <p>This information has not been evaluated by the US Food and Drug Administration, nor has it gone through the rigorous double-blind studies required before a particular product can be deemed truly beneficial or potentially dangerous and prescribed in the treatment of any condition or disease.</p>
                          <h3>ENTIRE AGREEMENT</h3>
                          <p>If a court finds any portion of this Agreement unenforceable, the rest of this Agreement will continue to apply. This is the entire agreement between you and the Company relating to the site and this Agreement replaces all prior written or oral agreements that may have existed between us. You cannot transfer or assign your rights or obligations under this Agreement to anyone without our written permission. Our failure to enforce any provision of this Agreement does not waive our right to enforce the same provision in the future. The headings contained in this Agreement are for informational purposes only, but are not, themselves, enforceable provisions of this Agreement.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
				<Footer />
			</div>
	</div>
    )
  }
}